version: "3"
services:
  api:
    image: idealley/ers-api
    depends_on:
      - mongodb
      - redis
    ports: 
      - 3030:3030

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:alpine
    volumes:
      - redis:/data/
    networks: 
      - redis-host
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  # nginx:
  #   image: nginx:stable-alpine
  #   depends_on:
  #     - api
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - "3040:80"
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "100MB"
  #       max-file: "3"

networks:
  redis-host:
    driver: bridge

volumes:
  mongodb:
  redis:

