const axios = require('axios');
/**
 * 
 * @param {*} url - base url
 * @param {*} token - Bearer token
 */
const HTTP = (url, token = null) =>
  axios.create(
    {
      baseURL: url,
      headers: 
        token 
          ? {
            Authorization: `Bearer ${token}` // The token is generated by a hook
          }
          : {}
    }
  );

module.exports = HTTP;