const axios = require('axios');
const dotenv = require('dotenv');
dotenv.load();

const eid = process.env.NODE_ENV === 'production' ? process.env.SPOTME_PROD_APP : process.env.SPOTME_DEV_APP;
const nlpServer = process.env.NLP_SERVER;
const recommenderServer = process.env.RECOMMENDER_SERVER;
/**
 * 
 * @param {String} url - base url
 * @param {String} token - Bearer token
 */
const HTTP = (url, token = null) =>
  axios.create({
    baseURL: url,
    headers: token ?
      {
        Authorization: `Bearer ${token}` // The token is generated by a hook
      } :
      {}
  });

const k4Client = HTTP('https://k4.ersnet.org/prod/v2/Front');
const spotmeClient = HTTP(`https://ds.4pax.com/api/v1/event-proxy/${eid}/nodehandlers/ers/notify?accredited_link_token=${process.env.SPOTME_NOTIFICATION_KEY}`);
const nlpClient = HTTP(nlpServer);
const recommenderClient = HTTP(recommenderServer);

module.exports = {
  HTTP,
  k4Client,
  spotmeClient,
  nlpClient,
  recommenderClient
};
