const axios = require('axios');
/**
 * 
 * @param {*} url - base url
 * @param {*} token - Bearer token
 */
const HTTP = (url, token = null) =>
  axios.create(
    {
      baseURL: url,
      headers: 
        token 
          ? {
            Authorization: `Bearer ${token}` // The token is generated by a hook
          }
          : {}
    }
  );

const k4Client = HTTP('https://k4.ersnet.org/prod/v2/Front');

module.exports = {
  HTTP,
  k4Client
};