module.exports=[
  'ContactId',
  // 'Adonix',
  'Title',
  'AcademicTitle',
  'LastName',
  'FirstName',
  'BirthDate',
  'Gender',
  'SmtpAddress1',
  'SmtpAddress2',
  'PhotoUrl',
  'Comments',
  'PortalUsername',
  'MainStreet1',
  'MainStreet2',
  'MainStreet3',
  'MainStreet4',
  'MainPostalCode',
  'MainCity',
  'MainStateCode',
  'MainCountryCode',
  'MainCountryName',
  'MbshipStatus',
  // 'JournalStreet1',
  // 'JournalStreet2',
  // 'JournalStreet3',
  // 'JournalStreet4',
  // 'JournalPostalCode',
  // 'JournalCity',
  // 'JournalStateCode',
  // 'JournalCountryCode',
  // 'BillToStreet1',
  // 'BillToStreet2',
  // 'BillToStreet3',
  // 'BillToStreet4',
  // 'BillToPostalCode',
  // 'BillToCity',
  // 'BillToStateCode',
  // 'BillToCountryCode',
  'Phone1',
  'Phone2',
  'Mobile',
  'Fax',
  'InfosByEmail',
  'InfosByPostmail',
  'VisibleInDirectory',
  'IsErsStaff',
  'IsVip',
  'CreationDate',
  'CreatedBy',
  'CanAccessLearningResources',
  'MainCountry',
  // 'JournalCountry',
  // 'BillToCountry',
  'Staff',
  'Roles',
  // 'Preferences',
  'Changes',
  'Duplicates',
  'Merges',
  'FullNameAndId',
  'Diseases',
  'Methods'
];