module.exports = {
  title: false,
  subTitle: false,
  slug: false,
  tags: false,
  contentType: false,
  type: false,
  typeColor: false,
  flags: [{ 
    text: false, 
    color: false 
  }],
  ebusDate: false,
  eventDate: false,
  eventEndDate: false,
  eventLocation: false,
  leadParagraph: false,
  body: false,
  articleOneColumn: false,
  displayModifiedOnDate: false,
  doNotDisplayCreatedOn: false,
  doNotDisplayCreatedOnOnHomepage: false,
  comments: false,
  image: false,
  imageDescription: false,
  itemImageAlignment: false,
  itemImageBackgroundSize: false,
  imageSize: false,
  highResImage: false,
  highResImageDescription: false,
  imageAlignment: false,
  video: false,
  author: false,
  category: {
    id: false,
    ref: false,
    title: false,
    qname: false,
    typeQName: false
  },
  category2: [{
    id: false,
    ref: false,
    title: false,
    qname: false,
    typeQName: false
  }],
  related: false,
  deadline: false,
  earlybirdDeadline: false,
  extendedDeadline: false,
  openingDate: false,
  programme: false,
  programmeButtonText: false,
  programmeNotice: false,
  practicalInfo: false,
  practicalInfoButton: false,
  technicalInfo: false,
  popUp: false,
  popUpText: false,
  feeList: { 
    junior: false, 
    ersMember: false, 
    nonErsMember: false, 
    industry: false 
  },
  cancellationPolicy: false,
  travelInfo: false,
  organisers: false,
  faculty: false,
  sponsors: [{ 
    text: false, 
    image: false 
  }],
  sponsorsAlliances: [{ 
    text: false, 
    image: false 
  }],
  documents: false,
  disclosure: false,
  rulesAndRegulations: false,
  deadlines: { 
    applicationDeadline: false, 
    applicationDeadline2: false, 
    notification: false, 
    notification2: false, 
    startDate: false, 
    startDate2: false 
  },
  venue: { 
    name: false, 
    url: false, 
    streetAddress: false, 
    streetAddress2: false, 
    streetAddress3: false, 
    city: false, 
    postalCode: false, 
    country: false, 
    phoneNumber: false, 
    info: false 
  },
  ebusVenues: [{ 
    name: false, 
    url: false, 
    streetAddress: false, 
    streetAddress2: false, 
    streetAddress3: false, 
    city: false, 
    postalCode: false, 
    country: false, 
    phoneNumber: false, 
    info: false 
  }],
  suggestedAccommodation: [{ 
    name: false, 
    url: false, 
    streetAddress: false, 
    streetAddress2: false, 
    streetAddress3: false, 
    city: false, 
    postalCode: false, 
    country: false, 
    phoneNumber: false, 
    info: false 
  }],
  registerButton: { 
    link: false, 
    text: false 
  },
  bursaryApplication: { 
    text: false, 
    deadline: false, 
    notificationOfResults: false, 
    applyButtonUrl: false 
  },
  mentorship: { 
    text: false, 
    deadline: false, 
    notificationOfResults: false, 
    applyButtonUrl: false 
  },
  abstracts: { 
    text: false, 
    deadline: false, 
    notificationOfResults: false, 
    applyButtonUrl: false 
  },
  availableOnHomepage: false,
  mainNews: false,
  featuredCourse: false,
  featuredFunding: false,
  featuredCalendarItem: false,
  nonErsCalendarItem: false,
  ersEndorsedEvent: false,
  ersDeadline: false,
  fullyBooked: false,
  displayOrder: false,
  loc: { 
    lat: false, 
    long: false 
  },
  eventDates: false,
  startDateTimestamp: false,
  startDate: false,
  endDate: false,
  createdOn: false,
  modifiedOn: false,
  calendar: {
    year: false,
    month: false,
    timestamp: false
  },
  ms:  false,
  shortLead:  false,
  hasRelatedArticles: false,
  hasAuthor: false,
  salutation: false,
  firstName: false,
  lastName: false,
  url: false,
  uri: false,
  unPublished: false,
  _system: false,
  _qname: false,
  _statistics: false
};