module.exports = {
  title: false,
  slug: false,
  author: false,
  journal: false,
  journalLink: false,
  leadParagraph: false,
  shortLead: false,
  digestType: false,
  digestAuthor: false,
  url: false,
  uri: false,
  diseases: false,
  methods: false,
  comments: false,
  'unPublished': false,
  _system: false,
  _qname: false,
  _statistics: false
};
