module.exports = {    
  title: false,
  subTitle: false,
  slug: false,
  author: false,
  tags: false,
  contentType: false,
  type: false,
  typeColor: false,
  flags: [{ 
    text: false, 
    color: false 
  }],
  leadParagraph: false,
  shortLead:  false,
  body: false,
  displayModifiedOnDate: false,
  doNotDisplayCreatedOn: false,
  doNotDisplayCreatedOnOnHomepage: false,
  image: false,
  itemImageAlignment: false,
  itemImageBackgroundSize: false,
  imageSize: false,
  video: false,
  eventDate: false,
  eventEndDate: false,
  eventDates: false,
  eventLocation: false,
  fullyBooked: false,
  ms:  false,
  url: false,
  uri: false,
};    